//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orders
{
    using System;
    //using System.Data.Entity;
    //using System.Data.Entity.Infrastructure;
    using Microsoft.EntityFrameworkCore;

    public partial class OrdersContainer : DbContext
    {
        public OrdersContainer(DbContextOptions<OrdersContainer> options)
            : base(options)
        {
            this.Database.EnsureCreated();
        }
    
        //protected override void OnModelCreating(DbModelBuilder modelBuilder)
        //{
        //    throw new UnintentionalCodeFirstException();
        //}
    
        public DbSet<Order> OrderSet { get; set; }
        public DbSet<OrderDetail> OrderDetailSet { get; set; }
    }
}
